---
title: "gibbs_sampling"
author: "Yijin Wang"
date: "2023-04-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
library(lme4)
library(LaplacesDemon)
library(purrr)
library(MASS)
```

## load data

```{r}
load("hurricane.RData")
data <- hurricane %>% ungroup()
```

## fit a linear mixed effects model for starting values
```{r}
# decide initial values for mcmc by fitting a simple glm :)

glmm <- glmer(Wind.kt ~ Month + Season + Nature + 
                (1 +Wind_prev + Lat_change+ Long_change+Wind_change |ID),
              family = "gaussian", data = data)
summary(glmm)
```

```{r}
glmm_summary <- summary(glmm)
gamma_init <- glmm_summary$coefficients%>%as.matrix() %>%
  as.data.frame() %>% slice(-1) %>% pull(Estimate)
```

## Metropolis Hasting Random Walk

$$\begin{aligned} f(\sigma^2|B, \mu, \Sigma, \gamma, Y)\propto 
& \prod_{i=1}^{H} det(\sigma^2I_{n_i})^{-1/2}exp(-\frac{1}{2}(Y_i - D_{i}\beta_{i}-X_i\gamma)^\intercal(\sigma^2I_{n_i})^{-1}(Y_i - D_{i}\beta_{i}-X_i\gamma)) \times \\
& \frac{1}{\pi(\sigma^2+10^2)\sigma} \\
=& \frac{1}{\sigma^N}exp(-\frac{(Y-DB-X\gamma)^\intercal(Y-DB-X\gamma)}{2\sigma^2}) \times \\
& \frac{1}{\pi(\sigma^2+10^2)\sigma}\end{aligned}$$

```{r}
# our target distribution (posterior conditional distribution) for sigma^2
# is too complicated. Try random walk with Metropolis hasting
# Use normal distribution as transition function

#' posterior for sigma squared
#' @param sigma_squared double
#' @param Y full response vector in shape N x 1 where N is the total number of observations in the data set
#' @param D full design matrix for random effects for all hurricanes. Its shape is N x 5.
#' @param B full random effects coefficients matrix in shape 5 x H where H is the total number of hurricanes
#' @param X full design matrix for fixed effects for all hurricanes. Its shape is H x 3. 
#' @param gamma fixed effects coefficients matrix in shape 3 x 1. 
#' 
#' @return posterior value for sigma squared with the given matrices
sigma_squared_posterior <- function(sigma_squared, Y, D, B, X, gamma){
  N <- length(Y)
  
  mu_H <- rep(NA, N)
  for (i in 1:H){
    curr_hurricane_idx <- ith_hurricane_idx[[i]]
    mu_i <- D[curr_hurricane_idx,,drop = FALSE] %*% B[,i,drop = FALSE]
    mu_H[curr_hurricane_idx] <- mu_i
  }
  
  mu_H <- as.matrix(mu_H)
  
  Y_minus_mu <- Y-mu_H- X%*%gamma
  
  if (sigma_squared>0){
    sigma <- sqrt(sigma_squared)
    
  } else{
    return(0)
  }
  likelihood <- (1/(sigma^N)) *exp(t(Y_minus_mu)%*%(Y_minus_mu)/(-2*sigma_squared))
  prior<- (1/(sigma*pi*(sigma_squared + 100)))

  return (likelihood*prior)
}

```

```{r}
sigma_squared_log_posterior <- function(sigma_squared, Y, D, B, X, gamma, H, ith_hurricane_idx){
 
  N = length(Y)
  
  mu_H <- rep(NA, N)
  for (i in 1:H){
    curr_hurricane_idx <- ith_hurricane_idx[[i]]
    mu_i <- D[curr_hurricane_idx,,drop = FALSE] %*% B[,i,drop = FALSE]
    mu_H[curr_hurricane_idx] <- mu_i
  }
  
  mu_H <- as.matrix(mu_H)

  Y_minus_mu <- Y-mu_H- X%*%gamma
  
  if (sigma_squared>0){
    sigma <- sqrt(sigma_squared)
    
  } else{
    # avoid -inf :) 
    return(-1e10)
  }
  
  log_likelihood <- (-N)* log(sigma) + (t(Y_minus_mu)%*%(Y_minus_mu)/(-2*sigma_squared))
  log_prior <- -log(sigma*pi*(sigma_squared + 100))
  return (log_likelihood+log_prior)
}
```

```{r}
#' calculate next value for sigma squared in metropolis hasting random walk  
#' https://towardsdatascience.com/from-scratch-bayesian-inference-markov-chain-monte-carlo-and-metropolis-hastings-in-python-ef21a29e25a
#' @param curr current sigma squared value
#' @param a window size in transition distribution Unif(curr-a, curr+a)
#' @param Y full response vector in shape N x 1 where N is the total number of observations in the data set
#' @param D full design matrix for random effects for all hurricanes. Its shape is N x 5.
#' @param B full random effects coefficients matrix in shape 5 x H where H is the total number of hurricanes
#' @param X full design matrix for fixed effects for all hurricanes. Its shape is H x 16. 
#' @param gamma fixed effects coefficients matrix in shape 16 x 1. 
#' @param H integer number of hurricanes
#' @param ith_hurricane_idx list of list of integers indexes for observations for the ith hurricane
#' 
#' @return next value for sigma squared in metropolis hasting random walk  
metropolis_hasting_sigma_squared_next_val <- function(curr, a, Y, D, B, X, gamma, H, ith_hurricane_idx){
  
  prop <- curr + (runif(1)-0.5)*2*a
  
  prop_post <- sigma_squared_log_posterior(prop, Y, D, B, X, gamma, H, ith_hurricane_idx)
  
  curr_post <- sigma_squared_log_posterior(curr, Y, D, B, X, gamma, H, ith_hurricane_idx)
  
  posterior_ratio <- exp(prop_post - curr_post)
  
  # acceptance prob
  alpha = min(posterior_ratio, 1)
  
  # random sample from unif(0,1)
  u <- runif(n = 1)
  
  if (u < alpha) {
    # accept
   return (prop)
  } else {
    return (curr)
  }
}
```

```{r}
metropolis_hasting_sigma_squared <- function(start_sigma_squared, 
                                             numtocompute, 
                                             a = 2,
                                             Y, D, B, X, gamma, H, ith_hurricane_idx){
  chain <- rep(NA, numtocompute)
  chain[1] <- start_sigma_squared
  for (i in 2:numtocompute) {
    #print(i)
    chain[i] <- metropolis_hasting_sigma_squared_next_val(chain[i-1],a,Y, D, B, X, gamma, H, ith_hurricane_idx)
  }
  return (chain)
}
```

## starting values
```{r}
a <- 1
Y <- as.matrix(data$Wind.kt)
D <- data %>% mutate(intercept = 1) %>% dplyr::select(intercept, Wind_prev, Lat_change, Long_change, Wind_change) %>% as.matrix()
X <- data  %>%
  mutate(index =1:nrow(data))%>%
  group_by(index) %>%
  dplyr::select(Month, Season, Nature) %>%
  mutate(n = 1)%>% 
  pivot_wider(names_from = Month, values_from=n, values_fill=0) %>% 
  mutate(n = 1)%>% 
  pivot_wider(names_from = Nature, values_from=n, values_fill=0) %>% 
  ungroup() %>%
  dplyr::select( April, May, June, July, August, September, October, November, December, Season, ET,NR,SS,TS) %>%
  as.matrix()
r <- ranef(glmm) 
B <-  r$ID %>% as.matrix() %>% t() %>% as.matrix()
B[1,] <-B[1,] + 37.841607
gamma <- gamma_init %>% as.matrix() 
```

```{r}
chain <- metropolis_hasting_sigma_squared(start_sigma_squared = 27.2828, 
                                             numtocompute = 500, 
                                             a = 0.8, Y, D, B, X, gamma, H, ith_hurricane_idx)
```

```{r}
accept = 0
for (i in 2:500) {
  if (test[["chains"]][[3]][i] != test[["chains"]][[3]][i-1]) {
    accept = accept+1
  }
}
accept/500
```

```{r}
plot(chain, type='l')
#, ylim=c(9.008e-07, 10.08e-07))
```

```{r}
hist(chain, freq = F, nclass = 100)
```


## Gibbs Sampling

```{r}
X_with_id <- cbind(as.numeric(factor(data$ID)), X)
#number of hurricanes
H <- max(X_with_id[,1])
ith_hurricane_idx <- 1:H |>
  map(\(i) which(X_with_id[,1] == i))
```


```{r}
# to get B transpose --> need to transpose B
# B is 5 x H

#' calculate conditional posterior for B
#' 
#' @param D full design matrix for random effects for all hurricanes in shape N x 5.
#' @param sigma_squared a double for sigma squared value
#' @param A inverse of variance of beta's in shape 5 x 5.
#' @param X full design matrix for fixed effects for all hurricanes. Its shape is H x 16. 
#' @param gamma fixed effects coefficients matrix in shape 16 x 1. 
#' @param mu  mean of beta's in shape 5 x 1
#' @param H integer number of hurricanes
#' @param ith_hurricane_idx list of list of integers indexes for observations for the ith hurricane
#' 
#' @return posterior of B in shape 5 x H based on the given values
#'  
B_post <- function(D, sigma_squared, A, X, gamma, mu, H, ith_hurricane_idx){
  B <- NULL
  total_obs <- nrow(D)
  for (i in 1:H){
    curr_hurricane_idx <- ith_hurricane_idx[[i]]
    n_i <- length(curr_hurricane_idx)
    X_i <- X[curr_hurricane_idx,,drop = FALSE]
    Y_i <- Y[curr_hurricane_idx,,drop = FALSE]
    # retain matrix form
    D_i <- D[curr_hurricane_idx,,drop = FALSE] 
    
    M_i <- t(D_i)%*% ((1/sigma_squared)*diag(n_i)) %*% D_i + A
    
    N_i<- t(D_i)%*% ((1/sigma_squared)*diag(n_i)) %*% Y_i - t(D_i)%*% (1/sigma_squared*diag(n_i)) %*% X_i%*%gamma + A%*%mu
    
    B_i <- mvrnorm(1, mu = solve(M_i) %*% N_i, Sigma = solve(M_i))
    B <- cbind(B, B_i)
  }
  
  return (B)
}
```


```{r}
#' calculate conditional posterior for mu
#'
#' @param A inverse of variance of beta's in shape 5 x 5.
#' @param V variance-covariance matrix for mu in shape 5 x 5
#' @param B full random effects coefficients matrix in shape 5 x H where H is the total number of hurricanes
#' 
#' @return posterior of mu in shape 5 x 1 based on the given values
mu_post <- function(A, V, B){
  M <- H* A - solve(V)
  N <- 0
  for (i in 1:H){
    N <- N + A %*% B[,i,drop = FALSE]
  }
  mu <-  mvrnorm(1, mu = solve(M) %*% N, Sigma = solve(M))
  
  return(mu)
}
```

```{r}
#' calculate conditional posterior for A (inverse of Sigma)
#'
#' @param nu integer for degree of freedom
#' @param B full random effects coefficients matrix in shape 5 x H where H is the to
#' @param mu  mean of beta's in shape 5 x 1
#' @param S scale matrix for A in shape 5 x 5.
#' @param H integer number of hurricanes
#' 
#' @return posterior of A in shape 5 x 5 based on the given values
A_post <- function(nu, B, mu, S, H){
  df <- H + nu
  
  sum = 0
  for (i in 1:H){
    sum = sum + (B[,i,drop = FALSE] - mu) %*% t((B[,i,drop = FALSE] - mu))
  }
  
  scale <- solve(S+ sum)
  
  A <- matrixsampling::rwishart(n = 1, nu = df, Sigma = scale, checkSymmetry = F)
  
  A <- array(A[, , 1], dim=c(5, 5)) 
  return (A)
}
```

```{r}
#' calculate conditional posterior for gamma
#' 
#' @param X full design matrix for fixed effects for all hurricanes. Its shape is H x 16. 
#' @param Y full response vector in shape N x 1 where N is the total number of observations in the data set
#' @param D full design matrix for random effects for all hurricanes in shape N x 5.
#' @param B full random effects coefficients matrix in shape 5 x H where H is the total number of hurricanes
#' @param sigma_squared  a double for sigma squared value
#' @param H integer number of hurricanes
#' @param ith_hurricane_idx list of list of integers indexes for observations for the ith hurricane
#' 
#' @return  posterior of gamma in shape 16 x 1 based on the given values
gamma_post <- function(X,Y, D,B, sigma_squared, H, ith_hurricane_idx){
  M <- 0
  N <- 0
  for (i in 1:H){
    curr_hurricane_idx <- ith_hurricane_idx[[i]]
    n_i <- length(curr_hurricane_idx)
    X_i <- X[curr_hurricane_idx,,drop = FALSE]
    Y_i <- Y[curr_hurricane_idx,,drop = FALSE]
    D_i <- D[curr_hurricane_idx,,drop = FALSE]
    M = M + t(X_i) %*% ((1/sigma_squared)*diag(n_i)) %*% X_i
    
    N = N + t(X_i) %*% ((1/sigma_squared)*diag(n_i))  %*% Y_i - t(X_i) %*% (1/sigma_squared*diag(n_i)) %*% D_i %*% B[,i,drop = FALSE]
    
  }
  M = M+ 400*diag((dim(X)[2]))
  
  gamma <- mvrnorm(1, mu = solve(M) %*% N, Sigma = solve(M)) %>% as.matrix()
  
  return(gamma)
}
```


```{r}
test_sigma_squared_post <- function(Y, D, B , X, gamma, H, ith_hurricane_idx){
  
  shape <- (nrow(D)-1)/2
  
  mu_H <- rep(NA, N)
  for (i in 1:H){
    curr_hurricane_idx <- ith_hurricane_idx[[i]]
    mu_i <- D[curr_hurricane_idx,,drop = FALSE] %*% B[,i,drop = FALSE]
    mu_H[curr_hurricane_idx] <- mu_i
  }
  
  mu_H <- as.matrix(mu_H)

  Y_minus_mu <- Y-mu_H- X%*%gamma
  
  rate <-t(Y_minus_mu)%*%(Y_minus_mu)/2
  
  
  sigma_squared <- rinvgamma(1, shape = shape, scale = rate)
  
  return(sigma_squared)
}
```


```{r}
hurricane_gibbs_sampling <- function(start_sigma_squared, 
                                     start_A,
                                     start_gamma, 
                                     start_mu,
                                     V,
                                     S,
                                     X,
                                     D,
                                     Y,
                                     nitr = 100,
                                     nu = 5, 
                                     H, 
                                     ith_hurricane_idx){
  B_post_results <- list()
  mu_post_reulsts <- list()
  A_post_results <- list()
  gamma_post_results <- list()
  sigma_squared_post_results <- list()
  chains<-list()
  
  # B first
  B <- B_post(D, start_sigma_squared, start_A, X, start_gamma, start_mu, H, ith_hurricane_idx)
  mu <- mu_post(A = start_A, V= V, B = B)
  A <- A_post(nu = nu, B = B, mu = mu, S = S, H = H)
  gamma <- gamma_post(X = X, 
                      Y = Y, 
                      D = D,
                      B = B,
                      sigma_squared = start_sigma_squared,
                      H = H, 
                      ith_hurricane_idx = ith_hurricane_idx)
  
  sigma_squared_chain <- metropolis_hasting_sigma_squared(
      start_sigma_squared = start_sigma_squared, 
      numtocompute = 500, 
      a = 0.8, 
      Y = Y, 
      D = D, 
      B = B, 
      X = X, 
      gamma = gamma,
      H = H, 
      ith_hurricane_idx = ith_hurricane_idx)
     
  sigma_squared <- mean(sigma_squared_chain[400:500])
  
  B_post_results[[1]] <- B
  mu_post_reulsts[[1]] <- mu
  A_post_results[[1]] <- A
  gamma_post_results[[1]] <-gamma
  sigma_squared_post_results[[1]] <-sigma_squared
  chains[[1]] <- sigma_squared_chain
  
  for (i in 2:nitr){
    
    print(i)

    B <- B_post(D = D, 
                sigma_squared = sigma_squared_post_results[[i-1]], 
                A = A_post_results[[i-1]], 
                X = X, 
                gamma = gamma_post_results[[i-1]], 
                mu = mu_post_reulsts[[i-1]],
                H = H, 
                ith_hurricane_idx = ith_hurricane_idx)
    
    mu <- mu_post(A = A_post_results[[i-1]], 
                  V= V, 
                  B = B)
    A <- A_post(nu = nu, 
                B = B, 
                mu = mu, 
                S = S,
                H = H)
      
    gamma <- gamma_post(X = X,
                        Y = Y, 
                        D = D,
                        B = B,
                        sigma_squared = sigma_squared_post_results[[i-1]],
                        H = H, 
                        ith_hurricane_idx = ith_hurricane_idx)
    
    # sigma_squared on its own random walk
    sigma_squared_chain <- metropolis_hasting_sigma_squared(
      start_sigma_squared = sigma_squared_post_results[[i-1]], 
      numtocompute = 500, 
      a = 0.8, 
      Y = Y, 
      D = D, 
      B = B, 
      X = X, 
      gamma = gamma,
      H = H, 
      ith_hurricane_idx = ith_hurricane_idx)
     
    sigma_squared <- mean(sigma_squared_chain[400:500])
    
    # collect results
    B_post_results[[i]] <- B
    mu_post_reulsts[[i]] <- mu
    A_post_results[[i]] <- A
    gamma_post_results[[i]] <-gamma
    sigma_squared_post_results[[i]] <-sigma_squared
    chains[[i]] <- sigma_squared_chain
  }
  
  return(list(
    B = B_post_results,
    mu = mu_post_reulsts,
    A = A_post_results,
    gamma = gamma_post_results,
    sigma_squared = sigma_squared_post_results,
    chains = chains
  ))
  
}
```

```{r}
V <- .8 * diag(5)
V[lower.tri(V)] <- 0.1
V[upper.tri(V)] <- 0.1

S <- .7 * diag(5)
S[lower.tri(S)] <- 0.2
S[upper.tri(S)] <- 0.2

nitr <- 6000

set.seed(2)
test = hurricane_gibbs_sampling(start_sigma_squared = 27.2828, 
                                start_A = solve(S),
                                start_gamma = gamma, 
                                start_mu = rowMeans(B) %>% as.matrix(),
                                V = V ,
                                S = S,
                                X = X,
                                D = D,
                                Y = Y,
                                H = H, 
                                ith_hurricane_idx = ith_hurricane_idx,
                                nitr = nitr)
save(test,file = "test.RData")
```

```{r}
XYD <- list(X = X, Y = Y, D = D)
save(XYD,file = "XYD.RData")
```

## Gibbs sampling posterior plots
```{r}
jpeg(file="./mcmc_results_fig/gamma/gamma_1-4_chain.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(4,1),mar = c(2, 5, 1, 1))
for (i in 1:4){
  
  plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["gamma"]][[x]][i,1]), xlab = "", ylab = paste0("gamma_", i, "_value"))
}
dev.off()
```
```{r}
jpeg(file="./mcmc_results_fig/gamma/gamma_5-8_chain.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(4,1),mar = c(2, 5, 1, 1))
for (i in 5:8){
  
  plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["gamma"]][[x]][i,1]), xlab = "", ylab = paste0("gamma_", i, "_value"))
}
dev.off()
```

```{r}
#jpeg(file="./mcmc_results_fig/gamma/gamma_9-12_chain.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(4,1),mar = c(2, 5, 1, 1))
for (i in 9:12){
  
  plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["gamma"]][[x]][i,1]), xlab = "", ylab = paste0("gamma_", i, "_value"))
}
dev.off()
```

```{r}
jpeg(file="./mcmc_results_fig/gamma/gamma_13-14_chain.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(4,1),mar = c(2, 5, 1, 1))
for (i in 13:14){
  
  plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["gamma"]][[x]][i,1]), xlab = "", ylab = paste0("gamma_", i, "_value"))
}
dev.off()
```

```{r}
jpeg(file="./mcmc_results_fig/gamma/gamma_acf.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(5,3),mar = c(2, 5, 1, 1))
for (i in 1:14){
  ac <- acf(sapply(3001:nitr, function(x) test[["gamma"]][[x]][i,1]), lag.max = 300,plot = FALSE)
  plot(ac, ylab = paste0("gamma_", i, "_acf_value"))
}
dev.off()
```

```{r}
jpeg(file="./mcmc_results_fig/gamma/gamma_histograms.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(5,3),mar = c(2, 5, 1, 1))
for (i in 1:14){
  hist(freq = F, nclass = 100, sapply(3001:nitr, function(x) test[["gamma"]][[x]][i]), main= paste0("gamma_", i, "_value"))
}
dev.off()
```


```{r}
par(mfrow=c(5,1),mar = c(2, 5, 1, 1))
for (i in 1:5){
  plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["mu"]][[x]][i]), xlab = "", ylab = paste0("mu_", i-1, "_value"))
}
```

```{r}
par(mfrow=c(2,3),mar = c(2, 5, 1, 1))
for (i in 1:5){
  ac <- acf(sapply(3001:nitr, function(x) test[["mu"]][[x]][i]), lag.max = 300,plot = FALSE)
  plot(ac, ylab = paste0("mu_", i-1, "_acf_value"))
}
```

```{r}
jpeg(file="./mcmc_results_fig/mu/mu_histograms.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(2,3),mar = c(2, 5, 1, 1))
for (i in 1:5){
  hist(freq = F, nclass = 100, sapply(3001:nitr, function(x) test[["mu"]][[x]][i]), main= paste0("mu_", i-1, "_value"))
}
dev.off()
```


```{r}
beta_0 <- c()
beta_1 <- c()
beta_2 <- c()
beta_3 <- c()
beta_4 <- c()

for (i in 1:nitr){
  beta_0 <- c(beta_0, mean(test[["B"]][[i]][1,],na.rm = TRUE))
  beta_1 <- c(beta_1, mean(test[["B"]][[i]][2,],na.rm = TRUE))
  beta_2 <- c(beta_2, mean(test[["B"]][[i]][3,],na.rm = TRUE))
  beta_3 <- c(beta_3, mean(test[["B"]][[i]][4,],na.rm = TRUE))
  beta_4 <- c(beta_4, mean(test[["B"]][[i]][5,],na.rm = TRUE))
}
```

```{r}
par(mfrow=c(5,1),mar = c(2, 5, 1, 1))
for (i in 1:5){
  plot(eval(parse(text = paste0("beta_", i-1))), type='l', xlab = "", ylab = paste0("beta_", i-1, "_value"))
}
```

```{r}
par(mfrow=c(2,3),mar = c(2, 5, 1, 1))
for (i in 1:5){
  val <- eval(parse(text = paste0("beta_", i-1)))
  ac <- acf(val[3001:nitr], lag.max = 300,plot = FALSE)
  plot(ac, ylab = paste0("beta_", i-1, "_acf_value"))
}
```

```{r}
jpeg(file="./mcmc_results_fig/beta/beta_histograms.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(2,3),mar = c(2, 5, 1, 1))
for (i in 1:5){
  val <- eval(parse(text = paste0("beta_", i-1)))
  hist(val[3001:nitr], freq = F, nclass = 100, main =  paste0("beta_", i-1, "_value"))
}
dev.off()
```

```{r}
par(mfrow=c(5,1),mar = c(2, 5, 1, 1))
for (i in 1:5){
  plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["A"]][[x]][1,i]), xlab = "", ylab = paste0("A_[1,", i,"]", "_value"))
}
```
```{r}
par(mfrow=c(5,1),mar = c(2, 5, 1, 1))
for (i in 1:5){
  plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["A"]][[x]][2,i]), xlab = "", ylab = paste0("A_[2,", i,"]", "_value"))
}
```
```{r}
par(mfrow=c(5,1),mar = c(2, 5, 1, 1))
for (i in 1:5){
  plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["A"]][[x]][3,i]), xlab = "", ylab = paste0("A_[3,", i,"]", "_value"))
}
```

```{r}
par(mfrow=c(5,1),mar = c(2, 5, 1, 1))
for (i in 1:5){
  plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["A"]][[x]][4,i]), xlab = "", ylab = paste0("A_[4,", i,"]", "_value"))
}
```

```{r}
par(mfrow=c(5,1),mar = c(2, 5, 1, 1))
for (i in 1:5){
  plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["A"]][[x]][5,i]), xlab = "", ylab = paste0("A_[5,", i,"]", "_value"))
}
```

```{r}
jpeg(file="./mcmc_results_fig/A/A_1-3_rows_acf.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(3,5),mar = c(2, 5, 1, 1))

for (r in 1:3){
  for (i in 1:5){
    ac <- acf(sapply(3001:nitr, function(x) test[["A"]][[x]][r,i]), lag.max = 300,plot = FALSE)
    plot(ac, ylab = paste0("A_[",r,",", i,"]", "_acf_value"))
  }
}
dev.off()
```

```{r}
jpeg(file="./mcmc_results_fig/A/A_4-5_rows_acf.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(3,5),mar = c(2, 5, 1, 1))

for (r in 4:5){
  for (i in 1:5){
    ac <- acf(sapply(3001:nitr, function(x) test[["A"]][[x]][r,i]), lag.max = 300,plot = FALSE)
    plot(ac, ylab = paste0("A_[",r,",", i,"]", "_acf_value"))
  }
}
dev.off()
```

```{r}
jpeg(file="./mcmc_results_fig/A/A_1-3_rows_histograms.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(3,5),mar = c(2, 5, 1, 1))
for (r in 1:3){
  for (i in 1:5){
    hist(freq = F, nclass = 100, sapply(3001:nitr, function(x) test[["A"]][[x]][r,i]), main= paste0("A_[",r,",", i,"]", "_value"))
  }
}
dev.off()
```
```{r}
jpeg(file="./mcmc_results_fig/A/A_4-5_rows_histograms.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(3,5),mar = c(2, 5, 1, 1))
for (r in 4:5){
  for (i in 1:5){
    hist(freq = F, nclass = 100, sapply(3001:nitr, function(x) test[["A"]][[x]][r,i]), main= paste0("A_[",r,",", i,"]", "_value"))
  }
}
dev.off()
```


```{r}
jpeg(file="./mcmc_results_fig/sigma_squared/sigma_squared.png", width = 1200, height = 600, quality = 100)
par(mfrow=c(3,1),mar = c(2, 5, 1, 1))
plot(1:nitr, type='l', sapply(1:nitr, function(x) test[["sigma_squared"]][[x]][1]), xlab = "", ylab = "sigma_squared")
hist(freq = F, nclass = 100, sapply(3001:nitr, function(x) test[["sigma_squared"]][[x]][1]), main= "sigma_squared value")
 ac <- acf(sapply(3001:nitr, function(x) test[["sigma_squared"]][[x]][1]), lag.max = 300,plot = FALSE)
  plot(ac, ylab = "sigma_squared_acf_value")
dev.off()
```
```{r}

```



